name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Generate env file
        run: |
          echo "window._env_ = {" > ./public/env-config.js
          echo "  REACT_APP_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'," >> ./public/env-config.js
          echo "  REACT_APP_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./public/env-config.js
          echo "  REACT_APP_DATABASE_URL: '${{ secrets.FIREBASE_DATABASE_URL }}'," >> ./public/env-config.js
          echo "  REACT_APP_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./public/env-config.js
          echo "  REACT_APP_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./public/env-config.js
          echo "  REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./public/env-config.js
          echo "  REACT_APP_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'," >> ./public/env-config.js
          echo "  REACT_APP_GA_TRACKING_ID: '${{ secrets.GA_TRACKING_ID }}'" >> ./public/env-config.js
          echo "}" >> ./public/env-config.js
        
      - name: Build
        run: npm run build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build