name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        env:
          REACT_APP_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          REACT_APP_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        run: npm run build

      - name: Generate runtime config
        run: |
          mkdir -p ./build
          echo "window._env_ = {" > ./build/env-config.js
          echo "  REACT_APP_API_KEY: '${{ secrets.FIREBASE_API_KEY }}'," >> ./build/env-config.js
          echo "  REACT_APP_AUTH_DOMAIN: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./build/env-config.js
          echo "  REACT_APP_DATABASE_URL: '${{ secrets.FIREBASE_DATABASE_URL }}'," >> ./build/env-config.js
          echo "  REACT_APP_PROJECT_ID: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./build/env-config.js
          echo "  REACT_APP_STORAGE_BUCKET: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./build/env-config.js
          echo "  REACT_APP_MESSAGING_SENDER_ID: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./build/env-config.js
          echo "  REACT_APP_APP_ID: '${{ secrets.FIREBASE_APP_ID }}'," >> ./build/env-config.js
          echo "  REACT_APP_GA_TRACKING_ID: '${{ secrets.GA_TRACKING_ID }}'" >> ./build/env-config.js
          echo "};" >> ./build/env-config.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: true