name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate runtime config
        run: |
          echo "Generating runtime env-config.js..."
          touch ./build/env-config.js
          echo "window._env_ = {" >> ./build/env-config.js
          echo "  apiKey: \"${{ secrets.FIREBASE_API_KEY }}\"," >> ./build/env-config.js
          echo "  authDomain: \"${{ secrets.FIREBASE_AUTH_DOMAIN }}\"," >> ./build/env-config.js
          echo "  databaseURL: \"${{ secrets.FIREBASE_DATABASE_URL }}\"," >> ./build/env-config.js
          echo "  projectId: \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> ./build/env-config.js
          echo "  storageBucket: \"${{ secrets.FIREBASE_STORAGE_BUCKET }}\"," >> ./build/env-config.js
          echo "  messagingSenderId: \"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\"," >> ./build/env-config.js
          echo "  appId: \"${{ secrets.FIREBASE_APP_ID }}\"," >> ./build/env-config.js
          echo "  measurementId: \"${{ secrets.FIREBASE_MEASUREMENT_ID }}\"" >> ./build/env-config.js
          echo "};" >> ./build/env-config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
