name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Generate runtime config
        run: |
          mkdir -p ./build
          echo "window._env_ = {" > ./build/env-config.js
          echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> ./build/env-config.js
          echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> ./build/env-config.js
          echo "  databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}'," >> ./build/env-config.js
          echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> ./build/env-config.js
          echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> ./build/env-config.js
          echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> ./build/env-config.js
          echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'" >> ./build/env-config.js
          echo "};" >> ./build/env-config.js
          
      - name: Update index.html
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          cp ./build/env-config.js ./build/${REPO_NAME}-env-config.js  # Create a backup copy
          sed -i "s/<head>/<head><script src=\"env-config.js\"><\/script>/" ./build/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: true