name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Generate runtime config
        run: |
          mkdir -p ./build
          cat > ./build/env-config.js << 'EOF'
          window._env_ = {
            apiKey: "${{ secrets.FIREBASE_API_KEY }}",
            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
            databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
            appId: "${{ secrets.FIREBASE_APP_ID }}"
          };
          EOF

      - name: Verify config file
        run: |
          echo "Checking env-config.js exists and contents:"
          ls -la ./build/
          cat ./build/env-config.js
          
      - name: Update index.html
        run: |
          # Remove any existing script tag for env-config.js
          sed -i '/<script.*env-config.js.*>/d' ./build/index.html
          # Add the new script tag right after the head tag
          sed -i '/<head>/a \    <script src="/solshr/env-config.js"></script>' ./build/index.html
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true